CREATE TYPE datatype AS ENUM (
    'variable',
    'habit'
);

CREATE TABLE entries (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    date TIMESTAMPTZ DEFAULT now() NOT NULL, 
    type datatype NOT NULL, 
    variable TEXT NOT NULL, 
    value NUMERIC NOT NULL
);

CREATE INDEX date_index ON entries(date);